[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "scorpion"
authors = [{name = "Feser Manuel", email = "feser@ipk-gatersleben.de"}]
dynamic = ["version", "description"]